name: 'maia-wasm'
on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    working-directory: maia-wasm

jobs:
  wasm:
    name: Build and test (wasm)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Format
      run: cargo fmt -- --check
    - name: Clippy
      run: cargo clippy --all-targets --all-features -- -D warnings
    - name: Doc
      run: cargo doc
    - name: Install wasm32-unknown-unknown Rust target
      run: rustup target add wasm32-unknown-unknown
    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    - name: Build with wasm-pack
      run: wasm-pack build --target web
  x86_64:
    name: Build and test (x86_64)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: cargo test
      run: cargo test --verbose
  publish:
    name: Publish Rust crate
    runs-on: ubuntu-latest
    if: startsWith(github.event.ref, 'refs/tags/maia-wasm-')
    needs: [wasm, x86_64]
    steps:
    - name: Publish crate
      run: cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
